#improvments
1. building the neural network using NN module
2. using built-in activation function
3. using built-in loss function
4. using built-in optimizer

In [ ]:
# pytorch--nn--module

In [9]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [10]:
# create a dataset
features = torch.rand(10,5)

In [11]:
#create model
model = Model(features.shape[1])

In [ ]:
#call model for forward pass
#model.forward(features)  # automatically called 
model(features)

tensor([[0.3034],
        [0.4183],
        [0.3327],
        [0.4252],
        [0.3394],
        [0.4751],
        [0.3836],
        [0.3867],
        [0.3766],
        [0.4049]], grad_fn=<SigmoidBackward0>)

In [18]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3754, -0.3998, -0.3167,  0.3341, -0.4195]], requires_grad=True)

In [19]:
model.linear.bias

Parameter containing:
tensor([-0.3238], requires_grad=True)

In [ ]:
# for visualization #!pip install torchinfo
from torchinfo import summary

In [21]:
summary(model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# more complex NN

In [4]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [5]:
#create model class # using sequential containers
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.64745937, -0.41898889, -0.67870574, ..., -0.35646323,
         0.3349551 , -0.80121102],
       [ 0.60586067,  0.05227193,  0.7426147 , ...,  0.98515799,
         0.69452881,  0.41544866],
       [ 2.99286566,  0.53272809,  3.05340129, ...,  2.07590696,
         0.42774832,  0.72118512],
       ...,
       [ 0.04186665,  0.75111725,  0.0775894 , ...,  0.3416161 ,
        -0.33282464, -0.03315531],
       [ 0.4719833 , -0.32013906,  0.48539967, ...,  1.03969544,
         1.47995709,  1.18350436],
       [-1.26927702, -0.18220906, -1.26158818, ..., -0.75848214,
         0.45591768,  0.065709  ]], shape=(455, 30))

In [9]:
y_train

293    B
479    M
521    M
510    B
182    M
      ..
67     B
261    M
536    M
11     M
470    B
Name: diagnosis, Length: 455, dtype: str

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0])

### Numpy arrays to PyTorch tensors

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

In [16]:
### Defining the model

In [ ]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [19]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [31]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float

In [32]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_fn = nn.BCELoss()

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.float())

  # loss calculate
  loss = loss_fn(y_pred, y_train_tensor.float().unsqueeze(1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.0633498430252075
Epoch: 2, Loss: 0.7324163317680359
Epoch: 3, Loss: 0.558891773223877
Epoch: 4, Loss: 0.4665008783340454
Epoch: 5, Loss: 0.4093216061592102
Epoch: 6, Loss: 0.3698008060455322
Epoch: 7, Loss: 0.34046608209609985
Epoch: 8, Loss: 0.3175900876522064
Epoch: 9, Loss: 0.2990957796573639
Epoch: 10, Loss: 0.2837291359901428
Epoch: 11, Loss: 0.2706853449344635
Epoch: 12, Loss: 0.2594224512577057
Epoch: 13, Loss: 0.2495608925819397
Epoch: 14, Loss: 0.24082617461681366
Epoch: 15, Loss: 0.23301425576210022
Epoch: 16, Loss: 0.22596998512744904
Epoch: 17, Loss: 0.2195730060338974
Epoch: 18, Loss: 0.21372823417186737
Epoch: 19, Loss: 0.2083595246076584
Epoch: 20, Loss: 0.20340493321418762
Epoch: 21, Loss: 0.19881360232830048
Epoch: 22, Loss: 0.19454322755336761
Epoch: 23, Loss: 0.1905582994222641
Epoch: 24, Loss: 0.18682874739170074
Epoch: 25, Loss: 0.18332889676094055

In [34]:
# View weight and bias
print("Weight:", model.linear.weight)
print("Bias:", model.linear.bias)

Weight: Parameter containing:
tensor([[ 4.1870e-01,  7.2976e-02,  1.5958e-01,  1.9360e-01,  4.7033e-02,
          1.2121e-01,  1.2346e-01,  4.5364e-01, -8.0051e-02, -1.6420e-01,
          1.1343e-01,  9.5083e-02,  7.6693e-02,  1.4996e-01, -6.8259e-02,
         -6.0613e-05,  1.4261e-01, -4.4717e-02,  9.2054e-02,  5.3795e-02,
          4.4964e-01,  1.3927e-01,  2.5936e-01,  1.2483e-01,  2.0838e-01,
          6.2686e-02,  9.8636e-02,  2.9499e-01,  3.3094e-01,  8.0276e-02]],
       requires_grad=True)
Bias: Parameter containing:
tensor([-0.1098], requires_grad=True)

In [35]:
type(loss_fn)

torch.nn.modules.loss.BCELoss

 #        Evaluation

In [37]:
# model evaluation
with torch.no_grad():
  y_pred = model(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor.float()).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5203139185905457